Feature: Add prettier config
bornfight/cra-template-bornfight pull request #1
Opened 2020-05-11 13:01 UTC by JuraJuki

- adds prettierrc
- adds prettierignore

2020-05-11 13:02 UTC, renatoruk commented
https://github.com/bornfight/prettier 

Let's maybe use this one as a dependency, as this is our official config! What do you think?

2020-05-12 05:45 UTC, JuraJuki commented
Prettier is already a dependency from the redux-typescript template. I've only added the official config and an ignore file.

2020-05-12 06:51 UTC, renatoruk commented
Yes, yes, I see!

But, there are other ways to solve this in a way that's easy to upgrade in the long term. :) 

Of course, prettier config is a trivial example, but it's a good practice to do it consistently for all the dependencies that you can maintain on one place.

What I'm suggesting is listing the dependency in the `package.json`. Maybe it's not visible out of the box in the repository, but the repo actually exposes a [npm package](https://www.npmjs.com/package/@bornfight/prettier) which can be installed on other projects.

Therefore, we can use it as e.g.:
```JSON
{
  "dependencies": {
    "@bornfight/prettier": "^1.0.0.",
  },
  "prettier": "@bornfight/prettier"
}
```

Here is written in detail: https://prettier.io/docs/en/configuration.html#sharing-configurations

2020-05-12 09:00 UTC, JuraJuki commented
> Yes, yes, I see!
> 
> But, there are other ways to solve this in a way that's easy to upgrade in the long term. :)
> 
> Of course, prettier config is a trivial example, but it's a good practice to do it consistently for all the dependencies that you can maintain on one place.
> 
> What I'm suggesting is listing the dependency in the `package.json`. Maybe it's not visible out of the box in the repository, but the repo actually exposes a [npm package](https://www.npmjs.com/package/@bornfight/prettier) which can be installed on other projects.
> 
> Therefore, we can use it as e.g.:
> 
> ```json
> {
>   "dependencies": {
>     "@bornfight/prettier": "^1.0.0.",
>   },
>   "prettier": "@bornfight/prettier"
> }
> ```
> 
> Here is written in detail: https://prettier.io/docs/en/configuration.html#sharing-configurations

Oooh that's what you meant! Nice nice, very good...adding!

2020-05-12 09:05 UTC, JuraJuki commented
@renatoruk pls check again :)

2020-05-12 09:25 UTC, JuraJuki commented
@renatoruk I made a mistake by pushing cypress and package.json update on the same branch. Please review it in this PR. I will update the description :C

2020-05-13 10:27 UTC, renatoruk requested changes

2020-05-13 10:27 UTC, renatoruk commented on package.json
>    }
This should be in the `template.json` file. https://github.com/reduxjs/cra-template-redux-typescript/blob/master/template.json

https://create-react-app.dev/docs/custom-templates/#the-templatejson-file

2020-05-13 10:28 UTC, renatoruk commented
> @renatoruk I made a mistake by pushing cypress and package.json update on the same branch. Please review it in this PR. I will update the description :C

No worries, it's in the initial phase after all

2020-05-13 10:37 UTC, closed without merging